apiVersion: 1.0.0
metadata:
  name: voting-app-nodejsdb2-crw
components:
  - id: vscode/typescript-language-features/latest
    type: chePlugin
  - id: ms-vscode/node-debug2/latest
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: nodejs
        port: 3000
    memoryLimit: 512Mi
    type: dockerimage
    alias: nodejs
    image: 'installer.internal.net:5000/l4a/plugin-java8-rhel8:2.15-l4a'
    env:
      - name: PORT
        value: '3000'
      - name: POSTGRES_CONNECT_STRING
        value: 'postgres://admin:admin@new-postgresql.pdf-voting-app-demo.svc.cluster.local/db'
      - name: DB_SERVICE_HOST
        value: 'new-postgresql.pdf-voting-app-demo.svc.cluster.local'
      - name: DB_SERVICE_PORT
        value: '50000'
      - name: DB_NAME
        value: 'sampledb'
      - name: DB_USER
        value: 'db2inst1'
      - name: DB_PASS
        value: 'passw0rd'
commands:
  - name: 1. Run the web app (and download dependencies)
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/voting-app-nodejsdb2-crw'
        type: exec
        command: npm install; nodemon server.js
        component: nodejs
  - name: 2. Download dependencies
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/voting-app-nodejsdb2-crw'
        type: exec
        command: npm install
        component: nodejs
  - name: 3. Run the web app
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/voting-app-nodejsdb2-crw'
        type: exec
        command: nodemon server.js
        component: nodejs
  - name: 4. Run the web app (debugging enabled)
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/voting-app-nodejsdb2-crw'
        type: exec
        command: nodemon --inspect server.js
        component: nodejs
  - name: 5. Stop the web app
    actions:
      - type: exec
        command: 'node_server_pids=$(pgrep -fx ''.*nodemon (--inspect )?server.js'' | tr "\\n" " ") && echo "Stopping node server with PIDs: ${node_server_pids}" && kill -15 ${node_server_pids} &>/dev/null && echo ''Done.'''
        component: nodejs
  - name: Attach remote debugger
    actions:
      - referenceContent: |
          {
            "version": "0.2.0",
            "configurations": [
              {
                "type": "node",
                "request": "attach",
                "name": "Attach to Remote",
                "address": "localhost",
                "port": 9229,
                "localRoot": "${workspaceFolder}",
                "remoteRoot": "${workspaceFolder}"
              }
            ]
          }
        type: vscode-launch
